src/backend/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
    path('routes/',include(('routes.urls','routes'),namespace='routes')),
    path('registration/', include(('registration.urls','registration'),namespace='registration')),
    path('events/', include(('events.urls','events'),namespace='events')),
    path('guides/', include(('guides.urls','guides'),namespace='guides')),
    path('', TemplateView.as_view(template_name='index.html'),name='home')
]

src/backend/events/urls.py
from django.urls import path
from . import views
from .views import AjaxHandler
app_name = 'events'

urlpatterns = [
    path("",views.index,name="index"),
    path("add", views.add,name="add"),
    path("join",AjaxHandler.as_view())
]

src/backend/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path("",views.index,name="index"),
    path("<int:id>", views.sight,name="sight"),
    path("add", views.add,name="add")
]

src/backend/registration/urls.py
from django.urls import path, include
from . import views
from registration.views import Register
from django.views.generic import TemplateView
app_name = 'registration'
urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name="register"),

]

src/backend/events/models.py
from django.db import models

# Create your models here.

src/backend/events/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
import json
import os
import requests
from datetime import datetime
import sqlite3
from django.views.generic import View


class NewEventForm(forms.Form):
    name = forms.CharField(label="Название достопримечательности")
    date = forms.CharField(label="Дата встречи")
    type = forms.CharField(label="Тип встречи(открытая/закрытая")


def index(request):
    username = request.user.username
    my_events = {"open": [], "close": []}
    other_events = {"open": [], "close": []}
    with_me = []

    db = sqlite3.connect('db.sqlite3')
    c = db.cursor()
    c.execute("""SELECT * FROM events
    """)
    db.commit()
    for i in c.fetchall():
        event = {"Name": i[2], "Organisator": i[3], "Date": i[4],
                 "People": [x.strip(' ') for x in i[5].split(" ") if x]}
        if i[1] == 'open':
            if i[3] == username:
                my_events["open"].append(event)
            elif username in i[5].split(" "):
                with_me.append(event)
            else:
                other_events["open"].append(event)
        elif i[1] == 'close':
            if i[3] == username:
                my_events["close"].append(event)
                event["To_accept"] = [x.strip(' ') for x in i[6].split(" ") if x]
                print(event["To_accept"])
            elif username in i[5].split(" "):
                with_me.append(event)
            else:
                other_events["close"].append(event)

    db.close()

    return render(request, "events/index.html", {
        "my_events": my_events,
        "other_events": other_events,
        "with_me": with_me,
    })


def add(request):
    username = request.user.username
    if request.method == "POST":
        form = NewEventForm(request.POST)
        if form.is_valid():
            new_event = {"Organisator": username, "Name": form.cleaned_data["name"], "Date": form.cleaned_data["date"],
                         "People": []}
            if str(form.cleaned_data["type"]).upper() == "ОТКРЫТАЯ":
                db = sqlite3.connect('db.sqlite3')
                c = db.cursor()
                c.execute(
                    """INSERT INTO events (type,name,organisator,date,people,to_cofirm) 
                    VALUES ('open',?,?,?,'','')""",
                    (new_event["Name"], new_event["Organisator"], new_event["Date"]))
                db.commit()
                db.close()
            elif str(form.cleaned_data["type"]).upper() == "ЗАКРЫТАЯ":
                db = sqlite3.connect('db.sqlite3')
                c = db.cursor()
                c.execute(
                    """INSERT INTO events (type,name,organisator,date,people,to_cofirm) 
                    VALUES ('close',?,?,?,'','')""",
                    (new_event["Name"], new_event["Organisator"], new_event["Date"]))
                db.commit()
                db.close()

            return HttpResponseRedirect(reverse("events:index"))
        else:
            return render(request, "events/add.html", {
                "form": form
            })

    return render(request, "events/add.html", {
        "form": NewEventForm()
    })


class AjaxHandler(View):
    def get(self, request):
        type = request.headers.get('type')
        user = request.headers.get('user')
        date = str(request.headers.get('d'))
        organisator = request.headers.get('organisator')
        result = {}
        if type == "open" or type == "close":
            db = sqlite3.connect('db.sqlite3')
            c = db.cursor()
            c.execute("""SELECT * FROM events 
            WHERE date = ? AND organisator = ? AND type = ?""",
                      (date, organisator, type))
            event = c.fetchone()
            if type == 'open':
                people = [x.strip(' ') for x in event[5].split(" ") if x]
                if user not in people:
                    people.append(user)
                    people = " ".join(people)
                    c.execute("""UPDATE events SET people = ? 
                    WHERE date = ? AND organisator = ? AND type = ?""",
                              (people, date, organisator, type))

            elif type == 'close':
                people = [x.strip(' ') for x in event[6].split(" ") if x]
                if user not in people:
                    people.append(user)
                    people = " ".join(people)
                    c.execute("""UPDATE events SET to_cofirm = ? 
                    WHERE date = ? AND organisator = ? AND type = ?""",
                              (people, date, organisator, type))

            elif type == 'accept':
                people1 = [x.strip(' ') for x in event[5].split(" ") if x]
                people2 = [x.strip(' ') for x in event[6].split(" ") if x]
                if user not in people1 and user in people2:
                    people1.append(user)
                    people2.remove(user)
                    people1 = " ".join(people1)
                    people2 = " ".join(people2)
                    c.execute("""UPDATE events SET people = ?,to_cofirm = ?
                    WHERE date = ? AND organisator = ? AND type = ?""",
                              (people1, people1, date, organisator, type))
            db.commit()
            db.close()

        return JsonResponse(result)

src/backend/events/templates/events/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Добавть  достопримечательность</title>
    <link rel="stylesheet" href="{% static 'events/styles.css' %}">
</head>
<body>
    <h1>Добавить  собрание</h1>
    <form action="{% url 'events:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'events:index' %}">Назад</a>
</body>
</html>

src/backend/events/templates/events/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ивенты</title>
    <link rel="stylesheet" href="../../static/events/styles.css">
    <script src= "../../static/events/events.js"></script>

</head>
<body>
    {% csrf_token %}
    {% if user.is_authenticated %}
        <h1>Мои ивенты:</h1>
            <h2>Открытые:</h2>
                {% for event in my_events.open %}
                <div id="my_event">
                    <h3>Название: {{ event.Name }}</h3>
                    <h3>Дата: {{ event.Date }}</h3>
                    <h3>Участники:</h3>
                    <ul>
                    {% for p in event.People %}
                        <li>
                            {{ p }}
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                {% endfor %}


            <h2>Закрытые:</h2>
                {% for event in my_events.close %}
                <div id="my_event">
                    <h3>Название: {{ event.Name }}</h3>
                    <h3>Дата: {{ event.Date }}</h3>
                    <h3>Участники:</h3>
                    <ul>
                    {% for p in event.People %}
                        <li>
                            {{ p }}
                        </li>
                    {% endfor %}
                    </ul>

                    <h3>Заявки:</h3>
                    <ul>
                    {% for p in event.To_accept %}
                        <li>
                            {{ p }}
                            <button data-user={{ p }} data-org={{ event.Organisator }} data-date={{ event.Date }} data-type="accept" id="join">Принять заявку</button>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                {% endfor %}

        <a href="{% url 'events:add' %}">Добавить  собрание</a>


        <h1>Я учавствую:</h1>
                {% for event in with_me %}
                <div id="my_event">
                    <h3>Организатор: {{event.Organisator }}</h3>
                    <h3>Название: {{ event.Name }}</h3>
                    <h3>Дата: {{ event.Date }}</h3>
                    <h3>Участники:</h3>
                    <ul>
                    {% for p in event.People %}
                        <li>
                            {{ p }}
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                {% endfor %}


        <h1>Другие ивенты:</h1>
            <h2>Открытые:</h2>
                {% for event in other_events.open %}
                <div id="open_event">
                    <h3>Организатор: {{event.Organisator }}</h3>
                    <h3>Название: {{ event.Name }}</h3>
                    <h3>Дата: {{ event.Date }}</h3>
                    <h3>Участники:</h3>
                    <ul>
                    {% for p in event.People %}
                        <li>
                            {{ p }}
                        </li>
                        {% endfor %}
                    </ul>
                        {% if user.get_username not in event.People%}
                            <button data-user={{ user.get_username }} data-org={{ event.Organisator }} data-date={{ event.Date }} data-type="open" id="join">Присоединиться</button>
                        {% endif %}
                </div>
                {% endfor %}

        <h2>Закрытые:</h2>
                {% for event in other_events.close %}
                <div id="close_event">
                    <h3>Организатор: {{event.Organisator }}</h3>
                    <h3>Название: {{event.Name }}</h3>
                    <h3>Дата: {{ event.Date }}</h3>
                    <h3>Участники:</h3>
                    <ul>
                    {% for p in event.People %}
                        <li>
                            {{ p }}
                        </li>
                    {% endfor %}
                    </ul>
                        {% if user.get_username not in event.To_accept and user.get_username not in event.People%}
                            <button data-user={{ user.get_username }} data-org={{ event.Organisator }} data-date={{ event.Date }} data-type="close" id="join">Отправить заявку</button>
                        {% else %}
                            <h3>Вы уже отправили заявку</h3>
                        {% endif %}
                </div>
                {% endfor %}

    {% else %}
        <a href="{% url 'registration:register' %}">Register</a> │ <a href="{% url 'registration:login' %}">Login</a>
    {% endif %}
</body>
</html>