src/backend/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
    path('routes/',include(('routes.urls','routes'),namespace='routes')),
    path('registration/', include(('registration.urls','registration'),namespace='registration')),
    path('events/', include(('events.urls','events'),namespace='events')),
    path('guides/', include(('guides.urls','guides'),namespace='guides')),
    path('', TemplateView.as_view(template_name='index.html'),name='home')
]

src/backend/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path("",views.index,name="index"),
    path("<int:id>", views.sight,name="sight"),
    path("add", views.add,name="add")
]

src/backend/routes/urls.py
from django.urls import path
from . import views
app_name = 'routes'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>", views.route, name="route")
]

src/backend/routes/models.py
from django.db import models

# Create your models here.

src/backend/routes/admin.py
from django.contrib import admin

# Register your models here.

src/backend/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "routes"

src/backend/routes/tests.py
from django.test import TestCase

# Create your tests here.

src/backend/routes/views.py
from django.shortcuts import render
import json
import os
import requests

with open("routes/data/routes.json", "r", encoding="utf-8") as f:
    routes = json.load(f)
routes = routes["Routes"]["items"]


def index(request):
    return render(request, "routes/index.html", {
        "routes": routes
    })


def route(request, id):
    route = routes[id]

    points = []

    for i in route["Points"]:
        try:
            lat, long = map(float, i.split(','))
            points.append([lat, long])
        except:
            r = requests.get(
                f'https://geocode-maps.yandex.ru/1.x/?format=json&apikey=d0c0fdfa-9ad7-4c7b-bc8c-d155a8326543&geocode=Ростов‑на‑Дону,{i}')
            r = r.json()
            long, lat = map(float, r["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["Point"][
                "pos"].split(" "))
            points.append([lat, long])
        print(points)
    return render(request, "routes/route.html", {
        "route": route,
        "points": points
    })

src/backend/routes/templates/routes/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Маршруты</title>
    <link rel="stylesheet" href="{% static 'routes/styles.css' %}">
</head>
<body id="routes">
    {% for route in routes %}
        <div id="route">
            <a href="{% url 'routes:route'  route.id%}">
                <h1>{{ route.Name }}</h1>
            </a>
            <h3>{{ route.Description }}</h3>
        </div>
    {% endfor %}
</body>
</html>

src/backend/routes/templates/routes/route.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ route.Name }}</title>
    <link rel="stylesheet" href="{% static 'routes/styles.css' %}">
    <script src="https://api-maps.yandex.ru/2.1/?apikey=d0c0fdfa-9ad7-4c7b-bc8c-d155a8326543&lang=ru_RU" type="text/javascript">
    </script>
    <script type="text/javascript">
    // Функция ymaps.ready() будет вызвана, когда
    // загрузятся все компоненты API, а также когда будет готово DOM-дерево.
    ymaps.ready(init);
    function init(){
        // Создание карты.
        var myMap = new ymaps.Map("map", {
            // Координаты центра карты.
            // Порядок по умолчанию: «широта, долгота».
            // Чтобы не определять координаты центра карты вручную,
            // воспользуйтесь инструментом Определение координат.
            center: [47.221142, 39.727215],
            // Уровень масштабирования. Допустимые значения:
            // от 0 (весь мир) до 19.
            zoom: 10,
            controls: ["zoomControl"]
        });

        var multiRoute = new ymaps.multiRouter.MultiRoute({
                // Точки маршрута. Точки могут быть заданы как координатами, так и адресом.
                referencePoints: {{ points }},
            params: {
      // Тип маршрута: на общественном транспорте.
      routingMode: "pedestrian"
            }
            },{
            routeActiveStrokeWidth: 5,
            routeActiveStrokeStyle: 'solid',
            boundsAutoApply: true,
            routeStrokeStyle: 'dot',
            routeStrokeWidth: 0,

    });
        myMap.geoObjects.add(multiRoute);



    }
</script>
</head>
<body>
    <h1>{{ route.Name }}</h1>
    <h3>{{ route.Description }}</h3>

    <div id="map" style="width: 600px; height: 400px"></div>
</body>
</html>