src/backend/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
    path('routes/',include(('routes.urls','routes'),namespace='routes')),
    path('registration/', include(('registration.urls','registration'),namespace='registration')),
    path('events/', include(('events.urls','events'),namespace='events')),
    path('guides/', include(('guides.urls','guides'),namespace='guides')),
    path('', TemplateView.as_view(template_name='index.html'),name='home')
]

src/backend/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path("",views.index,name="index"),
    path("<int:id>", views.sight,name="sight"),
    path("add", views.add,name="add")
]

src/backend/posts/models.py
from django.db import models

# Create your models here.

src/backend/posts/views.py
from django.shortcuts import render
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import json
import os
import requests


class NewSightForm(forms.Form):
    name = forms.CharField(label="Название достопримечательности")
    location = forms.CharField(label="Адрес достопримечательности")
    description = forms.CharField(label="Описание достопримечательности", widget=forms.Textarea)


with open("posts/data/Sights.json", "r", encoding="utf-8") as f:
    posts = json.load(f)
posts = posts["Sights"]["items"]


def index(request):
    return render(request, "posts/index.html", {
        "posts": posts
    })


def sight(request, id):
    sight = posts[id]
    images = []
    try:
        for file in os.listdir(f'posts/static/Photos/{posts[id]["Name"]}/'):
            if ".jpg" in file.lower():
                images.append(f'/Photos/{posts[id]["Name"]}/{file}')
    except:
        pass

    try:
        lat, long = map(float, sight["Location"].split(','))
    except:
        r = requests.get(
            f'https://geocode-maps.yandex.ru/1.x/?format=json&apikey=d0c0fdfa-9ad7-4c7b-bc8c-d155a8326543&geocode=Ростов‑на‑Дону,{sight["Location"]}')
        r = r.json()
        long, lat = map(float,
                        r["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]["Point"]["pos"].split(
                            " "))

    return render(request, "posts/sight.html", {
        "sight": sight,
        "images": images,
        "lat": lat,
        "long": long
    })


def add(request):
    if request.method == "POST":
        form = NewSightForm(request.POST)
        if form.is_valid():
            with open("posts/data/added_sights.json", "r") as f:
                sights = json.load(f)
            new_sight = {"Name": form.cleaned_data["name"], "Location": form.cleaned_data["location"],
                         "Description": form.cleaned_data["description"]}
            sights["Sights"]["items"].append(new_sight)
            with open('posts/data/added_sights.json', 'w', encoding='utf-8') as f:
                json.dump(sights, f)
            return HttpResponseRedirect(reverse("posts:index"))
        else:
            return render(request, "posts/add.html", {
                "form": form
            })

    return render(request, "posts/add.html", {
        "form": NewSightForm()
    })

src/backend/posts/templates/posts/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Добавть  достопримечательность</title>
    <link rel="stylesheet" href="{% static 'posts/styles.css' %}">
</head>
<body>
    <h1>Добавть  достопримечательность</h1>
    <form action="{% url 'posts:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'posts:index' %}">Назад</a>
</body>
</html>

src/backend/posts/templates/posts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Достопримечательности</title>
    <link rel="stylesheet" href="{% static 'posts/styles.css' %}">
</head>
<body id="sights">
    {% for post in posts %}
        <div id="sight">
            <a href="{% url 'posts:sight'  post.id%}">
                <h1>{{ post.Name }}</h1>
            </a>
            <h3>{{ post.Location }}</h3>
            <h3>{{ post.Description }}</h3>
        </div>
    {% endfor %}

    <a href="{% url 'posts:add' %}">Добавить  достопримечательность</a>
</body>
</html>

src/backend/posts/templates/posts/sight.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ sight.Name }}</title>
    <link rel="stylesheet" href="{% static 'posts/styles.css' %}">
    <script src="https://api-maps.yandex.ru/2.1/?apikey=d0c0fdfa-9ad7-4c7b-bc8c-d155a8326543&lang=ru_RU" type="text/javascript">
    </script>
    <script type="text/javascript">
    // Функция ymaps.ready() будет вызвана, когда
    // загрузятся все компоненты API, а также когда будет готово DOM-дерево.
    ymaps.ready(init);
    function init(){
        // Создание карты.
        var myMap = new ymaps.Map("map", {
            // Координаты центра карты.
            // Порядок по умолчанию: «широта, долгота».
            // Чтобы не определять координаты центра карты вручную,
            // воспользуйтесь инструментом Определение координат.
            center: [{{lat}}, {{long}}],
            // Уровень масштабирования. Допустимые значения:
            // от 0 (весь мир) до 19.
            zoom: 16,
            controls: ["zoomControl"]
        });

        var placemark = new ymaps.Placemark([{{ lat }}, {{ long }}],{
        });
        myMap.geoObjects.add(placemark);

    }
</script>
</head>
<body>
    <h1>{{ sight.Name }}</h1>
    <h3>{{ sight.Description }}</h3>

    {% for image in images %}
        <img src={% static image %}>
    {% endfor %}
    <div id="map" style="width: 600px; height: 400px"></div>
</body>
</html>