src/backend/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
    path('routes/',include(('routes.urls','routes'),namespace='routes')),
    path('registration/', include(('registration.urls','registration'),namespace='registration')),
    path('events/', include(('events.urls','events'),namespace='events')),
    path('guides/', include(('guides.urls','guides'),namespace='guides')),
    path('', TemplateView.as_view(template_name='index.html'),name='home')
]

src/backend/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path("",views.index,name="index"),
    path("<int:id>", views.sight,name="sight"),
    path("add", views.add,name="add")
]

src/backend/registration/urls.py
from django.urls import path, include
from . import views
from registration.views import Register
from django.views.generic import TemplateView
app_name = 'registration'
urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name="register"),

]

src/backend/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        h1 {
            text-align: center;
        }
    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <span class="navbar-text"></span>
        {% if user.is_authenticated %}
            <a href="{% url 'registration:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'registration:register' %}">Register</a> │ <a href="{% url 'registration:login' %}">Login</a>
    {% endif %}
    </span>

    <h1><a><a href="{% url 'posts:index' %}">Достопримечательности</a></a></h1>
    <h1><a><a href="{% url 'routes:index' %}">Марштуруты</a></a></h1>
    <h1><a><a href="{% url 'events:index' %}">Ивенты</a></a></h1>
    <h1><a><a href="{% url 'guides:index' %}">Гиды</a></a></h1>
</body>
</html>